// src/components/core/inputs/SelectComboInput.vue
<template>
  <div>
    <div class="relative">
      <div class="flex z-10 bg-white rounded-lg border-2">
        <div class="flex z-10 w-2/3">
          <input
            :class="{
              'w-full ml-4 p-[14px] text-lg text-right bg-white border-none outline-none ring-none': true,
              ...className
            }"
            name="input"
            @change="updateInput"
            type="text"
            v-model="input"
          />
        </div>

        <div class="flex w-1/3 z-10 border-l-2" @click="toggleList">
          <div class="flex-col py-2 pl-2 m-auto w-full">
            <h3 class="text-md font-bold leading-4">{{select.key || ''}}</h3>
          </div>

          <div class="flex my-auto mr-3 w-8">
            <ChevronUpDownIcon aria-hidden="true" class="w-8 h-7" />
          </div>
        </div>
      </div>

      <div
        :class="{
          'overflow-y-scroll absolute -right-1 -left-1 z-20 flex-col p-1 max-h-[200px] bg-white rounded-lg border-2 shadow-lg': true,
          visible: toggleActive === true,
          invisible: toggleActive === false,
        }"
      >
        <div
          v-for="(item, index) in options"
          :key="index"
          class="hover:bg-gray-200 active:bg-gray-200 rounded-lg p-4"
          @click="updateSelect(item)"
        >
          <h3 class="text-lg font-bold leading-4">{{ item.key || ''}}</h3>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { ChevronUpDownIcon } from '@heroicons/vue/20/solid'

export default {
  props: ["options", "onChange", "containerClassName", "className", "error", "validation"],

  components: {
    ChevronUpDownIcon,
  },

  data() {
    return {
      toggleActive: false,
      input: '',
      prevInput: '',
      select: this.options[0] || {},
      prevSelect: this.options[0] || {},
    }
  },

  methods: {
    toggleList() {
      this.toggleActive = !this.toggleActive
    },
    updateInput() {
      if (this.prevInput === this.input) return
      this.prevInput = this.input
      this.onChange({
        input: this.input,
        select: this.select.value,
      })
    },
    updateSelect(option: any) {
      this.toggleList()
      if (this.prevSelect === option) return
      this.select = option
      this.input = option.default
      this.prevSelect = this.select
      this.onChange({
        input: this.input,
        select: this.select.value,
      })
    },
  },

  mounted() {
    this.select = this.options[0]
    this.input = this.select.default
  },
};
</script>

// packages/ui/components/input/SelectComboInput.tsx
import clsx from 'clsx'
import { ChangeEvent, useEffect, useState } from 'react'
import { FieldPathValue, FieldValues, Path, Validate } from 'react-hook-form'

import { usePrevious } from '@croncat-ui/utils'

export interface ComboInputSelectValue {
  select: string
  input: string
}

export interface ComboInputSelectOption {
  key: string
  value: string
  default: string
}

export interface ComboInputSelectProps<
  FV extends FieldValues,
  FieldName extends Path<FV>
> {
  options: ComboInputSelectOption[]
  onChange: (data: ComboInputSelectValue) => void
  containerClassName?: string
  className?: string
  error?: boolean
  validation?: Validate<FieldPathValue<FV, FieldName>>[]
}

export const ComboInputSelect = <
  FV extends FieldValues,
  FieldName extends Path<FV>
>({
  options,
  onChange,
  containerClassName,
  className,
  error,
  validation,
  ...props
}: ComboInputSelectProps<FV, FieldName>) => {
  const [state, setState] = useState(() => {
    const first = options[0]
    return { input: first.default, select: first.value }
  })

  // TOOD: Finish!
  const validate = validation?.reduce(
    (a, v) => ({ ...a, [v.toString()]: v }),
    {}
  )

  const lastState = usePrevious(state)

  const updateInput = (e: ChangeEvent<HTMLInputElement>) => {
    setState({ ...state, input: e.target.value })
  }
  const updateSelect = (e: ChangeEvent<HTMLSelectElement>) => {
    setState({ ...state, select: e.target.value })
  }

  useEffect(() => {
    if (lastState?.select !== state.select) {
      const index = options.findIndex((v) => v.value === state.select)
      setState({ ...state, input: options[index].default })
    }
    onChange(state)
  }, [state])

  return (
    <div
      className={clsx(
        'flex w-full text-lg text-right bg-white rounded-lg border-2 focus-within:outline-none focus-within:ring-2 ring-offset-0 transition border-default',
        {
          'ring-2 ring-red-700 shadow-md shadow-red-400': error,
          'ring-transparent': !error,
        },
        containerClassName
      )}
    >
      <input
        className={clsx(
          'py-[14px] px-3 w-2/3 text-lg bg-transparent border-none outline-none ring-none',
          className
        )}
        name="input"
        onChange={updateInput}
        type="text"
        value={state.input}
        {...props}
      />
      <select
        className={clsx(
          'py-[14px] px-3 w-1/3 text-body bg-transparent border-l-2 focus:outline-none focus:ring-none border-default'
        )}
        name="select"
        onChange={updateSelect}
        value={state.select}
        {...props}
      >
        {options.map((option, index) => (
          <option key={index} value={option.value}>
            {option.key}
          </option>
        ))}
      </select>
    </div>
  )
}
