// packages/ui/components/input/TextInput.tsx
import clsx from 'clsx'
import { ComponentProps } from 'react'
import {
  FieldError,
  FieldPathValue,
  FieldValues,
  Path,
  UseFormRegister,
  Validate,
} from 'react-hook-form'

export interface TextInputProps<
  FV extends FieldValues,
  FieldName extends Path<FV>
> extends Omit<ComponentProps<'input'>, 'type' | 'required'> {
  fieldName: FieldName
  register: UseFormRegister<FV>
  validation?: Validate<FieldPathValue<FV, FieldName>>[]
  error?: FieldError
  required?: boolean
}

/**
 * @param fieldName  - the field name for the value that this will contain.
 * @param register   - the register function returned by `useForm`.
 * @param error      - any errors that have occured during validation of this
 *                     input.
 * @param validation - a list of functions that, when given the current value
 *                     of this field, return true if the value is valid and an
 *                     error message otherwise.
 */
export const TextInput = <FV extends FieldValues, FieldName extends Path<FV>>({
  fieldName,
  register,
  error,
  validation,
  className,
  required,
  ...rest
}: TextInputProps<FV, FieldName>) => {
  const validate = validation?.reduce(
    (a, v) => ({ ...a, [v.toString()]: v }),
    {}
  )

  return (
    <input
      className={clsx(
        'py-2 px-3 w-full bg-transparent rounded-lg border focus:outline-none focus:ring-1 ring-brand ring-offset-0 transition border-default body-text',
        { 'ring-1 ring-error': error },
        className
      )}
      type="text"
      {...rest}
      {...register(fieldName, { required: required && 'Required', validate })}
    />
  )
}

// src/components/core/inputs/TextInput.vue
<template>
  <input
    :class="{
      'py-2 px-3 w-full bg-transparent rounded-lg border focus:outline-none focus:ring-1 ring-brand ring-offset-0 transition border-default body-text': true,
      'ring-1 ring-error': error,
      ...className
    }"
    :required="required"
    type="text"
  />
</template>

<script lang="ts">
export interface TextInputProps {
  // validation?: any
  error?: any
  required?: boolean
}

export default {
  props: ["className", "error", "required"],
};
</script>
