// packages/ui/components/TokenSelector.tsx
import { Asset } from '@chain-registry/types'
import { ChevronUpDownIcon } from '@heroicons/react/24/outline'
import clsx from 'clsx'
import { useState } from 'react'

import { LogoFromImage } from '@croncat-ui/ui'

export interface TokenSelectorValue {
  value: any
}

export interface TokenSelectorOption {
  key: string
  value: any
}

export interface TokenSelectorProps {
  options: TokenSelectorOption[]
  onChange: (value: any) => void
  containerClassName?: string
  className?: string
}

export const TokenSelector = ({
  options,
  onChange,
  containerClassName,
  className,
  ...props
}: TokenSelectorProps) => {
  const [toggleActive, setToggleActive] = useState(false)
  const [state, setState] = useState(options[0])

  const toggleList = () => {
    setToggleActive(!toggleActive)
  }

  const updateSelect = (item: any) => {
    setState({ ...item })
    toggleList()
    onChange(state)
  }

  return (
    <div>
      <div className="relative">
        <div
          className="flex z-10 bg-white rounded-lg border-2"
          onClick={toggleList}
        >
          <TokenItem value={state.value} />

          <div className="flex my-auto mr-3 w-8">
            <ChevronUpDownIcon />
          </div>
        </div>

        <div
          className={clsx(
            'overflow-y-scroll absolute top-12 -right-1 -left-1 z-20 flex-col p-1 max-h-[200px] bg-white rounded-lg border-2 shadow-lg',
            {
              visible: toggleActive === true,
              invisible: toggleActive === false,
            }
          )}
        >
          {options.map((item, index) => (
            <div
              key={index}
              className="bg-white hover:bg-gray-200 active:bg-gray-200 rounded-lg"
              onClick={() => {
                updateSelect(item)
              }}
            >
              <TokenItem value={item.value} />
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

interface TokenItemProps {
  value: Asset
}

const TokenItem = ({ value }: TokenItemProps) => (
  <div className="flex px-2 w-full cursor-pointer">
    <div className="flex py-2 mr-2" style={{ minWidth: '42px' }}>
      <LogoFromImage
        className="block"
        rounded={true}
        size="42"
        src={value?.logo_URIs?.png || ''}
      />
    </div>
    <div className="flex-col py-2 m-auto w-full">
      <h3 className="text-lg font-bold leading-4">{value.symbol}</h3>
    </div>
  </div>
)

// src/components/core/inputs/TokenSelector.vue
<template>
  <div>
    <div class="relative">
      <div
        class="flex z-10 bg-white rounded-lg border-2"
        @click="toggleList"
      >
        <Token :value="state" />

        <div class="flex my-auto mr-3 w-8">
          <ChevronUpDownIcon />
        </div>
      </div>

      <div
        :class="{
          'overflow-y-scroll absolute top-12 -right-1 -left-1 z-20 flex-col p-1 max-h-[200px] bg-white rounded-lg border-2 shadow-lg': true,
          visible: toggleActive === true,
          invisible: toggleActive === false,
        }"
      >
        <div
          v-for="(item, index) in options"
          :key="index"
          class="hover:bg-gray-200 active:bg-gray-200 rounded-lg"
          @click="updateSelect(item)"
        >
          <Token :value="item" />
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { ChevronUpDownIcon } from '@heroicons/vue/24/outline'
import Token from '../display/Token.vue'
import Balance from '../display/Balance.vue'
import LogoFromImage from '../display/LogoFromImage.vue'

export default {
  props: ["options", "onChange"],

  components: {
    ChevronUpDownIcon,
    Token,
    Balance,
    LogoFromImage,
  },

  data() {
    return {
      toggleActive: false,
      state: this.options[0],
    }
  },

  methods: {
    toggleList() {
      this.toggleActive = !this.toggleActive
    },
    updateSelect(item: any) {
      this.state = item
      this.onChange(item)
      this.toggleList()
    },
    assignDefault() {
      if ((!this.state || !this.state.symbol) && this.options.length > 0) this.state = this.options[0]
      else this.state = this.options[0]
    },
  },

  watch: {
    options: ['assignDefault'],
  },
};
</script>
