// packages/actions/components/CadenceBoundary.tsx
import {
  AdjustmentsVerticalIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowUturnDownIcon,
  BoltIcon,
  CalendarDaysIcon,
  ClockIcon,
  RectangleStackIcon,
} from '@heroicons/react/24/outline'
import { assets } from 'chain-registry'
import { useEffect, useState } from 'react'
import { Controller, useFormContext } from 'react-hook-form'
import { useTranslation } from 'react-i18next'

import { Interval } from '@croncat-ui/actions'
import {
  AddressInput,
  ComboInputSelect,
  InputLabel,
  InputSubtext,
  NumberInput,
  SelectList,
} from '@croncat-ui/ui'
import {
  validateAddress,
  validatePositive,
  validateRequired,
} from '@croncat-ui/utils'

export const CadenceBoundaryComponent = () => {
  const {
    register,
    watch,
    control,
    formState: { errors },
  } = useFormContext()
  const { t } = useTranslation()
  const fieldNamePrefix = ''

  const assetList = assets.find(({ chain_name }) => chain_name === 'juno')
  const tokens = assetList?.assets || []

  const intervalUxOptions = [
    {
      key: 'cron_daily',
      value: {
        sort: 1,
        Icon: CalendarDaysIcon,
        title: 'Every Day',
        type: 'cron_daily',
        data: {
          intervalType: Interval.Cron,
          intervalValue: '0 0 * * *',
        },
      },
    },
    {
      key: 'cron_hourly',
      value: {
        sort: 2,
        Icon: ClockIcon,
        title: 'Every Hour',
        type: 'cron_hourly',
        data: {
          intervalType: Interval.Cron,
          intervalValue: '0 * * * *',
        },
      },
    },
    {
      key: 'cron_minutely',
      value: {
        sort: 3,
        Icon: ClockIcon,
        title: 'Every Minute',
        type: 'cron_minutely',
        data: {
          intervalType: Interval.Cron,
          intervalValue: '* * * * *',
        },
      },
    },
    {
      key: 'blocks_1000',
      value: {
        sort: 4,
        Icon: RectangleStackIcon,
        title: 'Every 1000 Blocks',
        type: 'blocks_1000',
        data: {
          intervalType: Interval.Block,
          intervalValue: 1000,
        },
      },
    },
    {
      key: 'balance_gt',
      value: {
        sort: 5,
        Icon: ArrowTrendingUpIcon,
        title: 'When balance above',
        type: 'balance_gt',
        data: {
          intervalType: Interval.Immediate,
          intervalValue: null,
        },
      },
    },
    {
      key: 'balance_lt',
      value: {
        sort: 6,
        Icon: ArrowTrendingDownIcon,
        title: 'When balance below',
        type: 'balance_lt',
        data: {
          intervalType: Interval.Immediate,
          intervalValue: null,
        },
      },
    },
    {
      key: 'custom',
      value: {
        sort: 10,
        Icon: AdjustmentsVerticalIcon,
        title: 'Custom',
        type: 'custom',
        data: {
          intervalType: null,
          intervalValue: null,
        },
      },
    },
  ]

  // immediately, pick a time, pick a block, Funds run out
  const boundaryOptions: any = [
    {
      key: 'cron_custom',
      value: {
        sort: 9,
        Icon: ClockIcon,
        title: 'Pick a time',
        type: 'cron_custom',
        data: {
          intervalType: Interval.Cron,
          intervalValue: '',
        },
      },
    },
    {
      key: 'blocks_custom',
      value: {
        sort: 11,
        Icon: RectangleStackIcon,
        title: 'Pick a block',
        type: 'blocks_custom',
        data: {
          intervalType: Interval.Block,
          intervalValue: 0, // TODO: Get current block + 1000
        },
      },
    },
  ]
  const boundaryStartOptions = [
    {
      key: 'immediate',
      value: {
        sort: 1,
        Icon: BoltIcon,
        title: 'Immediately',
        type: 'immediate',
        data: {
          intervalType: Interval.Immediate,
          intervalValue: '',
        },
      },
    },
  ].concat(boundaryOptions)
  const boundaryEndOptions = [
    {
      key: 'event_funds_lt',
      value: {
        sort: 1,
        Icon: ArrowUturnDownIcon,
        title: 'When funds run out',
        type: 'event_funds_lt',
        data: {
          intervalType: Interval.Immediate,
          intervalValue: '',
        },
        // rules: [] // TODO:
      },
    },
  ].concat(boundaryOptions)

  // TODO: Add for custom
  const customUxOptions = [
    // {
    //   type: Interval.Once,
    //   title: 'One Time',
    // },
    // {
    //   type: Interval.Immediate,
    //   title: 'Immediately',
    // },
    {
      key: t('form.block_interval'),
      value: Interval.Block,
      default: '100',
    },
    {
      key: t('form.cron_spec'),
      value: Interval.Cron,
      default: '0 0 * * *', // daily
    },
  ]

  // TODO: Add for custom
  const balanceLogicOptions = [
    {
      key: tokens[0].symbol,
      value: tokens[0].name,
      default: '1',
    },
    {
      key: tokens[1].symbol,
      value: tokens[1].name,
      default: '1',
    },
  ]

  const [intervalOption, setIntervalOption] = useState(intervalUxOptions[0])
  const [intervalCustom, setIntervalCustom] = useState({
    input: customUxOptions[0].default,
    select: customUxOptions[0].value,
  })
  const [selectedStart, setSelectedStart] = useState(boundaryStartOptions[0])
  const [selectedEnd, setSelectedEnd] = useState(boundaryEndOptions[0])

  useEffect(() => {
    const subscription = watch((value, { name, type }) => {
      if (name === 'interval' && type === 'change')
        setIntervalOption(value[name])
      if (name === 'interval_custom' && type === 'change')
        setIntervalCustom(value[name])
      if (name === 'boundary_start' && type === 'change')
        setSelectedStart(value[name])
      if (name === 'boundary_end' && type === 'change')
        setSelectedEnd(value[name])
    })
    return () => subscription.unsubscribe()
  }, [watch])

  // TODO:
  // - Get current block height for selected networks

  return (
    <div aria-details="dca fields" className="my-8 mb-24">
      <h3 className="mb-2 text-xl">{t('form.cadence_how_often')}</h3>
      <Controller
        control={control}
        defaultValue={intervalUxOptions[0]}
        name="interval"
        render={({ field: { onChange } }) => {
          return (
            <SelectList
              name="interval"
              onChange={onChange}
              options={intervalUxOptions}
              // error={errors?.interval}
              // validation={[validateRequired, validatePositive]}
            />
          )
        }}
        rules={{ required: true }}
      />

      {intervalOption.key === 'custom' ? (
        <div className="mt-4">
          {intervalCustom.select === Interval.Block ? (
            <InputLabel className="mb-2" name={t('form.block_interval')} />
          ) : (
            ''
          )}
          {intervalCustom.select === Interval.Cron ? (
            <InputLabel className="mb-2" name={t('form.cron_spec')} />
          ) : (
            ''
          )}
          <Controller
            control={control}
            name="interval_custom"
            render={({ field: { onChange } }) => {
              return (
                <ComboInputSelect
                  error={errors?.interval_custom}
                  onChange={onChange}
                  options={customUxOptions}
                  validation={[validateRequired, validatePositive]}
                />
              )
            }}
            rules={{ required: true }}
          />

          {intervalCustom.select === Interval.Block ? (
            <InputSubtext
              text={
                t('form.every') +
                ' ' +
                intervalCustom.input +
                ' ' +
                t('form.blocks')
              }
            />
          ) : (
            ''
          )}
          {intervalCustom.select === Interval.Cron ? (
            <small>
              {t('info.crontab_validator')}{' '}
              <a
                className="text-blue-600 underline"
                href="https://crontab.guru/"
                rel="noreferrer"
                target="_blank"
              >
                {t('info.crontab_guru')}
              </a>
            </small>
          ) : (
            ''
          )}
          {errors.interval_custom ? (
            <InputSubtext error={true} text={t('error.interval_custom')} />
          ) : (
            ''
          )}
        </div>
      ) : (
        ''
      )}

      {intervalOption.value.type === 'balance_gt' ||
      intervalOption.value.type === 'balance_lt' ? (
        <div className="mt-4">
          <InputLabel
            className="mb-2"
            name={
              t('form.balance') +
              ' ' +
              (intervalOption.value.type === 'balance_gt'
                ? t('form.gt')
                : t('form.lt'))
            }
          />
          <Controller
            control={control}
            name="rule_balance"
            render={({ field: { onChange } }) => {
              return (
                <ComboInputSelect
                  error={errors?.rule_balance}
                  onChange={onChange}
                  options={balanceLogicOptions}
                  validation={[validateRequired, validatePositive]}
                />
              )
            }}
            rules={{ required: true }}
          />

          {errors.rule_balance ? (
            <InputSubtext error={true} text={t('error.rule_balance')} />
          ) : (
            ''
          )}

          <InputLabel
            className="mt-4 mb-2"
            name={t('form.wallet_address_watch')}
          />
          <AddressInput
            containerClassName="grow"
            disabled={false}
            error={errors?.rule_balance_address}
            fieldName={fieldNamePrefix + 'rule_balance_address'}
            register={register}
            validation={[validateRequired, validateAddress]}
          />

          {errors.rule_balance_address ? (
            <InputSubtext error={true} text={t('error.rule_balance_address')} />
          ) : (
            ''
          )}
        </div>
      ) : (
        ''
      )}

      <br />
      <br />

      <h3 className="mb-2 text-xl">{t('form.cadence_when_start')}</h3>
      <Controller
        control={control}
        defaultValue={boundaryStartOptions[0]}
        name="boundary_start"
        render={({ field: { onChange } }) => {
          return (
            <SelectList
              onChange={onChange}
              options={boundaryStartOptions}
              // error={errors?.boundary_start}
              // validation={[validateRequired, validatePositive]}
            />
          )
        }}
        rules={{ required: true }}
      />

      {selectedStart.key === 'cron_custom' ||
      selectedStart.key === 'blocks_custom' ? (
        <div className="mt-4">
          {selectedStart.key === 'blocks_custom' ? (
            <InputLabel className="mb-2" name={t('form.block_height')} />
          ) : (
            ''
          )}
          {selectedStart.key === 'cron_custom' ? (
            <InputLabel className="mb-2" name={t('form.timestamp')} />
          ) : (
            ''
          )}
          <NumberInput
            // TODO:
            // defaultValue={+new Date()}
            error={errors?.cadence_start_number}
            fieldName={'cadence_start_number'}
            register={register}
            sizing="full"
            validation={[validateRequired, validatePositive]}
          />

          {selectedStart.key === 'blocks_custom' ? (
            // TODO:
            <InputSubtext
              text={
                t('form.current') + ' ' + t('form.block_height') + ' 5,132,868'
              }
            />
          ) : (
            ''
          )}

          {errors.cadence_start_number &&
          selectedStart.key === 'blocks_custom' ? (
            <InputSubtext
              error={true}
              text={t('error.cadence_start_number_block')}
            />
          ) : (
            ''
          )}
          {errors.cadence_start_number &&
          selectedStart.key === 'cron_custom' ? (
            <InputSubtext
              error={true}
              text={t('error.cadence_start_number_ts')}
            />
          ) : (
            ''
          )}
        </div>
      ) : (
        ''
      )}

      <br />
      <br />

      <h3 className="mb-2 text-xl">{t('form.cadence_when_end')}</h3>
      <Controller
        control={control}
        defaultValue={boundaryEndOptions[0]}
        name="boundary_end"
        render={({ field: { onChange } }) => {
          return (
            <SelectList
              onChange={onChange}
              options={boundaryEndOptions}
              // error={errors?.boundary_end}
              // validation={[validateRequired, validatePositive]}
            />
          )
        }}
        rules={{ required: true }}
      />

      {selectedEnd.key === 'cron_custom' ||
      selectedEnd.key === 'blocks_custom' ? (
        <div className="mt-4">
          {selectedEnd.key === 'blocks_custom' ? (
            <InputLabel className="mb-2" name={t('form.block_height')} />
          ) : (
            ''
          )}
          {selectedEnd.key === 'cron_custom' ? (
            <InputLabel className="mb-2" name={t('form.timestamp')} />
          ) : (
            ''
          )}
          <NumberInput
            // TODO:
            // defaultValue={}
            error={errors?.cadence_end_number}
            fieldName={fieldNamePrefix + 'cadence_end_number'}
            register={register}
            sizing="full"
            validation={[validateRequired, validatePositive]}
          />

          {selectedEnd.key === 'blocks_custom' ? (
            // TODO:
            <InputSubtext
              text={
                t('form.current') + ' ' + t('form.block_height') + ' 5,132,868'
              }
            />
          ) : (
            ''
          )}

          {errors.cadence_end_number &&
          selectedStart.key === 'blocks_custom' ? (
            <InputSubtext
              error={true}
              text={t('error.cadence_end_number_block')}
            />
          ) : (
            ''
          )}
          {errors.cadence_end_number && selectedStart.key === 'cron_custom' ? (
            <InputSubtext
              error={true}
              text={t('error.cadence_end_number_ts')}
            />
          ) : (
            ''
          )}
        </div>
      ) : (
        ''
      )}
    </div>
  )
}

// src/components/forms/CadenceBoundary.vue
<template>
  <div aria-details="dca fields" class="my-8 mb-24">
    <h3 class="mb-2 text-xl">How often should this occur?</h3>
    <SelectList name="interval" :onChange="setIntervalOption" :options="intervalUxOptions" />

    <div v-if="intervalOption.type === 'custom'">
      <div class="mt-4">
        <SelectComboInput :onChange="setIntervalCustom" :options="customUxOptions" />

        <Subtext v-if="intervalCustom.select == Interval.Block" :text="`${'Every ' + intervalCustom.input + ' blocks'}`" />
        <small v-if="intervalCustom.select == Interval.Cron">
          Check and validate your string at
          <a
            class="text-blue-600 underline"
            href="https://crontab.guru/"
            rel="noreferrer"
            target="_blank"
          >
            CronTab Guru
          </a>
        </small>
        <Subtext v-if="errors.interval_custom" :error="true" :text="error.interval_custom" />
      </div>
    </div>

    <div v-if="intervalOption.type === 'has_balance_gte' || intervalOption.type === 'has_balance_lte'" class="mt-4">
      <Label class="mb-2" :name="`${'Balance ' + (intervalOption.type == 'has_balance_gte' ? 'Greater Than' : 'Less Than')}`" />
      <TokenInputSelector :onChange="setIntervalBalanceAsset" :options="availableTokens" />
      <Subtext v-if="errors.rule_balance" :error="true" :text="error.rule_balance" />
    
      <Label class="mt-4 mb-2" name="Wallet Address to Watch" />
      <AddressInput :default="watchAddress" containerclass="grow" :onChange="setIntervalBalanceAddress" :disabled="false" :error="errors.rule_balance_address" />
      <Subtext v-if="errors.rule_balance_address" :error="true" :text="error.rule_balance_address" />
    </div>

    <br />
    <br />

    <h3 class="mb-2 text-xl">When should this start?</h3>
    <SelectList :onChange="setBoundaryStart" :options="boundaryStartOptions" />

    <div v-if="selectedStart.type === 'Time' || selectedStart.type === 'Height'" class="mt-4">
      <Label v-if="selectedStart.type === 'Height'" class="mb-2" name="Block Height" />
      <!-- <Label v-if="selectedStart.type === 'Time'" class="mb-2" name="Timestamp" /> -->
      <template v-if="selectedStart.type === 'Time'">
        <DatePicker v-model="timestampStart" mode="dateTime" circle is24hr is-expanded>
          <template v-slot="{ inputValue, togglePopover }">
            <div @click="togglePopover()" class="flex gap-1 items-center py-[17px] px-3 font-mono text-sm bg-white rounded-lg border-2 focus-within:outline-none focus-within:ring-2 ring-offset-0 transition border-default">
              <CalendarDaysIcon class="mr-2 w-6 h-6" color="currentColor" />
              <input :value="inputValue" placeholder="Choose Start" class="w-full bg-transparent border-none outline-none ring-none body-text" readonly />
            </div>
          </template>
        </DatePicker>
      </template>
      <template v-if="selectedStart.type === 'Height'">
        <NumberInput :onChange="setBoundaryStartValue" :error="errors.cadence_start_number" sizing="full" />
      </template>

      <Subtext v-if="selectedStart.type === 'Height'" :text="recentBlockHeight" />
      <Subtext v-if="errors.cadence_start_number && selectedStart.type === 'Height'" :error="true" :text="error.cadence_start_number_block" />
      <Subtext v-if="errors.cadence_start_number && selectedStart.type === 'Time'" :error="true" :text="error.cadence_start_number_ts" />
    </div>

    <br />
    <br />

    <div v-if="intervalOption.type != 'once'">
      <h3 class="mb-2 text-xl">When should this end?</h3>
      <SelectList :onChange="setBoundaryEnd" :options="boundaryEndOptions" />

      <div v-if="selectedEnd.type === 'Time' || selectedEnd.type === 'Height'" class="mt-4">
        <Label v-if="selectedEnd.type === 'Height'" class="mb-2" name="Block Height" />
        <!-- <Label v-if="selectedEnd.type === 'Time'" class="mb-2" name="Timestamp" /> -->
        <template v-if="selectedEnd.type === 'Time'">
          <DatePicker v-model="timestampEnd" mode="dateTime" circle is24hr>
            <template v-slot="{ inputValue, togglePopover }">
              <div @click="togglePopover()"
                class="flex gap-1 items-center py-[17px] px-3 font-mono text-sm bg-white rounded-lg border-2 focus-within:outline-none focus-within:ring-2 ring-offset-0 transition border-default">
                <CalendarDaysIcon class="mr-2 w-6 h-6" color="currentColor" />
                <input :value="inputValue" placeholder="Choose End" class="w-full bg-transparent border-none outline-none ring-none body-text"
                  readonly />
              </div>
            </template>
          </DatePicker>
        </template>
        <template v-if="selectedEnd.type === 'Height'">
          <NumberInput :onChange="setBoundaryEndValue" :error="errors.cadence_end_number" sizing="full" />
        </template>

        <Subtext v-if="selectedEnd.type === 'Height'" :text="recentBlockHeight" />
        <Subtext v-if="errors.cadence_end_number && selectedStart.type === 'Height'" :error="true" :text="error.cadence_end_number_block" />
        <Subtext v-if="errors.cadence_end_number && selectedStart.type === 'Time'" :error="true" :text="error.cadence_end_number_ts" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { mapState, mapActions } from "pinia";
import { useMultiWallet } from "@/stores/multiWallet";
import { useTaskCreator } from "@/stores/taskCreator";
import {
  addCommas,
  getChainAssetList,
  getAssetByDenomOnChain,
  getDeployedContractsByChain,
  isCw20Asset,
  isNativeAsset,
} from '@/utils/helpers'
import type { Addr, Account, Asset, Boundary, GenericBalance } from "@/utils/types"
import { queriesCatalog } from "@/utils/mvpData"
import Label from '@/components/core/display/Label.vue'
import Subtext from '@/components/core/display/Subtext.vue'
import AddressInput from '@/components/core/inputs/AddressInput.vue'
import NumberInput from '@/components/core/inputs/NumberInput.vue'
import SelectList from '@/components/core/inputs/SelectList.vue'
import SelectComboInput from "../core/inputs/SelectComboInput.vue";
import TokenInputSelector from "../core/inputs/TokenInputSelector.vue";
import 'v-calendar/dist/style.css';
// https://github.com/nathanreyes/v-calendar
import { DatePicker } from 'v-calendar';
import {
  Interval,
  intervalUxOptions,
  boundaryOptions,
  boundaryStartOptions,
  boundaryEndOptions,
  customUxOptions,
} from "@/utils/taskHelpers"
import {
  CalendarDaysIcon,
} from '@heroicons/vue/24/outline'

export default {
  components: {
    AddressInput,
    CalendarDaysIcon,
    SelectComboInput,
    Label,
    Subtext,
    NumberInput,
    SelectList,
    TokenInputSelector,
    DatePicker,
  },

  data() {
    return {
      Interval,
      errors: {},
      blockHeight: 0,
      boundary: null as any | null,
      timestampStart: null,
      timestampEnd: null,
      signer: undefined as Account | undefined,
      availableTokens: [] as Asset[],
      watchToken: undefined as Asset | undefined,
      watchAddress: undefined as Addr | undefined,
      selectedStart: boundaryStartOptions[0],
      selectedEnd: boundaryEndOptions[0],
      intervalOption: intervalUxOptions[0],
      intervalCustom: {
        input: customUxOptions[0].default,
        select: customUxOptions[0].value,
      },
      intervalUxOptions,
      boundaryOptions,
      boundaryStartOptions,
      boundaryEndOptions,
      customUxOptions,
    }
  },

  computed: {
    ...mapState(useMultiWallet, ['networks', 'accounts']),
    ...mapState(useTaskCreator, ['task', 'context']),
    recentBlockHeight() {
      return `Recent Block Height ${addCommas(`${this.blockHeight}`)}`
    },
  },

  // TODO: Validations!
  methods: {
    ...mapActions(useMultiWallet, ['querier', 'getNetworkForAccount']),
    ...mapActions(useTaskCreator, ['updateTask', 'updateTaskContext']),
    setIntervalOption(interval: any) {
      let i: any = "Immediate"
      // "interval": "Once",
      // "interval": "Immediate",
      // "interval": { "Block": 123 },
      // "interval": { "Cron": "0 0 * * *" },
      switch (interval.data.intervalType) {
        case Interval.Once:
          i = "Once"
          break;
        case Interval.Immediate:
          i = "Immediate"
          break;
        case Interval.Block:
        case null:
          i = { "Block": interval.data.intervalValue || 100 }
          break;
        case Interval.Cron:
          i = { "Cron": interval.data.intervalValue }
          break;
        default:
          break;
      }

      if (i === 'Immediate' && (interval.type === 'has_balance_gte' || interval.type === 'has_balance_lte')) {
        // Set the watch address straight away with my signer as default:
        if (this.context?.signer_addr) this.setIntervalBalanceAddress(this.context.signer_addr)
      }

      this.updateTask({ interval: i })
      this.intervalOption = interval
    },
    setIntervalCustom(custom: any) {
      let i: any = "Immediate"
      // "interval": { "Block": 123 },
      // "interval": { "Cron": "0 0 * * *" },
      switch (custom.select) {
        case Interval.Block:
          i = { "Block": parseInt(custom.input) }
          break;
        case Interval.Cron:
          i = { "Cron": custom.input }
          break;
        default:
          break;
      }

      this.updateTask({ interval: i })
      this.intervalCustom = custom
    },
    setIntervalBalanceAsset(asset: any) {
      this.watchToken = asset
      this.setQuery_HasBalance()
    },
    setIntervalBalanceAddress(address: Addr) {
      this.watchAddress = address
      this.setQuery_HasBalance()
    },
    setQuery_HasBalance() {
      if (!this.watchAddress || !this.watchToken) return;
      const type = this.intervalOption.type
      const rawAsset = this.watchToken
      const chain = this.getNetworkForAccount({ address: this.watchAddress })
      const asset = getAssetByDenomOnChain(rawAsset.denom, chain)
      if (!asset) return;

      // balance logic if native/cw20 token
      // NOTE: How to check IBC balance?
      let required_balance = {}
      if (isNativeAsset(asset)) {
        required_balance = {
          native: [this.watchToken]
        }
      }
      if (isCw20Asset(asset)) {
        required_balance = {
          cw20: {
            address: asset.address || '',
            amount: this.watchToken.amount,
          }
        }
      }

      // Get the deployed rules contract for balances
      const deployed = getDeployedContractsByChain(chain)
      const contract_addr = deployed?.rules
      if (!contract_addr) return;

      const queryMsg = queriesCatalog.hasBalanceLogicType({
        contract_addr,
        address: this.watchAddress,
        required_balance: required_balance as GenericBalance,
        type,
      })

      // update the task with this query rule
      this.updateTask({ queries: [queryMsg] })
    },
    setBoundaryStart(value: any) {
      this.selectedStart = value

      // Reset any set fields if immediate
      if (value.type === 'immediate') {
        if (this.boundary.Height?.start) delete this.boundary.Height.start
        if (this.boundary.Time?.start) delete this.boundary.Time.start
      }

      // clean up if missing state
      if (this.boundary?.Height) {
        if (Object.keys(this.boundary.Height).length == 0) this.boundary = null
      }
      if (this.boundary?.Time) {
        if (Object.keys(this.boundary.Time).length == 0) this.boundary = null
      }

      if (this.boundary) this.updateTask({ boundary: { ...this.boundary } })
      else this.updateTask({ boundary: null })
    },
    setBoundaryEnd(value: any) {
      this.selectedEnd = value

      // Reset any set fields if immediate
      if (value.type === 'event_funds_lt') {
        if (this.boundary.Height?.end) delete this.boundary.Height.end
        if (this.boundary.Time?.end) delete this.boundary.Time.end
      }

      // clean up if missing state
      if (this.boundary?.Height) {
        if (Object.keys(this.boundary.Height).length == 0) this.boundary = null
      }
      if (this.boundary?.Time) {
        if (Object.keys(this.boundary.Time).length == 0) this.boundary = null
      }
      
      if (this.boundary) this.updateTask({ boundary: { ...this.boundary } })
      else this.updateTask({ boundary: null })
    },
    setBoundaryStartValue(v: any) {
      const value = v || this.timestampStart
      
      if (this.selectedStart.type === 'Height') {
        if (!this.boundary) this.boundary = {}
        if (this.boundary?.Time) delete this.boundary.Time
        this.boundary.Height = this.boundary.Height || {}
        this.boundary.Height.start = `${value}`
      }
      if (this.selectedStart.type === 'Time') {
        if (!this.boundary) this.boundary = {}
        if (this.boundary?.Height) delete this.boundary.Height
        this.boundary.Time = this.boundary.Time || {}
        this.boundary.Time.start = `${new Date(value).getTime() * 1000}`
      }

      this.updateTask({ boundary: { ...this.boundary } })
    },
    setBoundaryEndValue(v: any) {
      const value = v || this.timestampEnd

      if (this.selectedEnd.type === 'Height') {
        if (!this.boundary) this.boundary = {}
        if (this.boundary?.Time) delete this.boundary.Time
        this.boundary.Height = this.boundary.Height || {}
        this.boundary.Height.end = `${value}`
      }
      if (this.selectedEnd.type === 'Time') {
        if (!this.boundary) this.boundary = {}
        if (this.boundary?.Height) delete this.boundary.Height
        this.boundary.Time = this.boundary.Time || {}
        this.boundary.Time.end = `${new Date(value).getTime() * 1000}`
      }

      this.updateTask({ boundary: { ...this.boundary } })
    },
    async getCurrentBlockHeight() {
      const q = await this.querier(this.signer.chain.chain_name)
      const r = await q.status()
      if (r?.syncInfo?.latestBlockHeight) this.blockHeight = r.syncInfo.latestBlockHeight
      this.updateTaskContext({ blockHeight: this.blockHeight })
    },
  },

  mounted() {
    this.signer = this.accounts[0]
    // Get current "sender" account's chain name
    if (this.context?.signer_addr) {
      const signer = this.accounts.find((a: Account) => a.address === this.context.signer_addr)
      if (signer) this.signer = signer
    }
    if (!this.signer) return;

    // init defaults
    this.getCurrentBlockHeight()
    this.availableTokens = getChainAssetList(this.signer.chain)
    this.watchAddress = this.signer.address
    if (this.availableTokens) this.watchToken = this.availableTokens[0]
  },

  watch: {
    'timestampStart': ['setBoundaryStartValue'],
    'timestampEnd': ['setBoundaryEndValue'],
  },
};
</script>
